[package]
name = "copy-translator"
version = "0.1.0"
edition = "2018"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[dependencies]
cli-clipboard = "0.2" # a fork version of cliboard, add wayland support
egui = { path = "./egui/egui" }
egui_glium = { path = "./egui/egui_glium" }
eframe = { path = "./egui/eframe" }
epi = { path = "./egui/epi" }
glium = "0.30"
piet-common = "0.4.1"
online-api = { path = "./deepl-rs/online-api" }
tauri-hotkey = "0.1.2"
copypasta = "0.7.1"
enigo = { git = "https://github.com/enigo-rs/enigo" }
ico = "0.1.0"

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1"
