[package]
name = "copy-translator"
version = "0.1.0"
edition = "2018"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[dependencies]
cli-clipboard = "0.2" # a fork version of cliboard, add wayland support
eframe = { git = "https://github.com/zu1k/egui.git", branch = "copy-translator" }
egui = { git = "https://github.com/zu1k/egui.git", branch = "copy-translator" }
egui_glium = { git = "https://github.com/zu1k/egui.git", branch = "copy-translator" }
epi = { git = "https://github.com/zu1k/egui.git", branch = "copy-translator" }
enigo = { git = "https://github.com/enigo-rs/enigo" }
glium = "0.30"
deepl = { path = "./deepl", default-features = false } # features must be specified, `local` or `online`
piet-common = "0.4.1"
tauri-hotkey = "0.1.2"
copypasta = "0.7.1"
ico = "0.1.0"
rdev = "0.5.1"

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1"

[features]
default = ["local"]
online = ["deepl/online"]
local = ["deepl/local"]
persistence = ["eframe/persistence", "egui/persistence", "egui_glium/persistence", "epi/persistence"]
